apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: vouchers.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-serv
                port:
                  number: 3000
          - path: /api/vouchers/?(.*)
            pathType: Prefix
            backend:
              service:
                name: voucher-serv
                port:
                  number: 3000
          - path: /api/voucher_pool/?(.*)
            pathType: Prefix
            backend:
              service:
                name: voucher-serv
                port:
                  number: 3000
          - path: /api/redeem/?(.*)
            pathType: Prefix
            backend:
              service:
                name: redeem-serv
                port:
                  number: 3000
